const TarotCards = [
    {
        id: 1,
        name: "asilmis-adam",
        front: "Asılmış adam",
        revert: "Asılmış adam ters",
    },
    {
        id: 2,
        name: "tilsim-kralicesi",
        front: "Tılsımların Kraliçesi",
        revert: "Tılsımların Kraliçesi Ters",
    },
    {
        id: 3,
        name: "seytan",
        front: "Şeytan",
        revert: "Şeytan Ters",
    },
    {
        id: 4,
        name: "kuvvet",
        front: "Kuvvet",
        revert: "Kuvvet Ters",
    },
    {
        id: 5,
        name: "dünya",
        front: "Dünya",
        revert: "Dünya Ters",
    },
    {
        id: 6,
        name: "ay",
        front: "Ay",
        revert: "Ay Ters",
    },
    {
        id: 7,
        name: "kupa-asi",
        front: "Kupaların Ası",
        revert: "Kupaların Ası Ters",
    },
    {
        id: 8,
        name: "kiliclarin-prensi",
        front: "Kılıçların Prensi",
        revert: "Kılıçların Prensi Ters",
    },
    {
        id: 9,
        name: "tilsim-prensi",
        front: "Tılsımların Prensi",
        revert: "Tılsımların Prensi Ters",
    },
    {
        id: 10,
        name: "savas-arabasi",
        front: "Savaş Arabası",
        revert: "Savaş Arabası Ters",
    },
    {
        id: 11,
        name: "olum",
        front: "Ölüm",
        revert: "Ölüm Ters",
    },
    {
        id: 12,
        name: "buyucu",
        front: "Büyücü",
        revert: "Büyücü Ters",
    },
    {
        id: 13,
        name: "degnek-krali",
        front: "Değnek Kralı",
        revert: "Değnek Kralı Ters",
    },
    {
        id: 14,
        name: "kiliclarin-krali",
        front: "Kılıçların Kralı",
        revert: "Kılıçların Kralı Ters",
    },
    {
        id: 15,
        name: "kiliclarin-yedilisi",
        front: "Kılıçların Yedilisi",
        revert: "Kılıçların Yedilisi Ters",
    },
    {
        id: 16,
        name: "degnek-dortlusu",
        front: "Değnek Dörtlüsü",
        revert: "Değnek Dörtlüsü Ters",
    },
    {
        id: 17,
        name: "kupa-dokuzlusu",
        front: "Kupaların Dokuzlusu",
        revert: "Kupaların Dokuzlusu Ters",
    },
    {
        id: 18,
        name: "kiliclarin-dortlusu",
        front: "Kılıçların Dörtlüsü",
        revert: "Kılıçların Dörtlüsü Ters",
    },
    {
        id: 19,
        name: "degnek-ikilisi",
        front: "Değnek İkilisi",
        revert: "Değnek İkilisi Ters",
    },
    {
        id: 20,
        name: "tilsim-sekizlisi",
        front: "Tılsımların Sekizlisi",
        revert: "Tılsımların Sekizlisi Ters",
    },
    {
        id: 21,
        name: "kiliclarin-altilisi",
        front: "Kılıçların Altılısı",
        revert: "Kılıçların Altılısı Ters",
    },
    {
        id: 22,
        name: "tilsim-dortlusu",
        front: "Tılsımların Dörtlüsü",
        revert: "Tılsımların Dörtlüsü Ters",
    },
    {
        id: 23,
        name: "kupa-sovalyesi",
        front: "Kupaların Şövalyesi",
        revert: "Kupaların Şövalyesi Ters",
    },
    {
        id: 24,
        name: "kiliclarin-kralicesi",
        front: "Kılıçların Kraliçesi",
        revert: "Kılıçların Kraliçesi Ters",
    },
    {
        id: 25,
        name: "imparatorice",
        front: "İmparatoriçe",
        revert: "İmparatoriçe Ters",
    },
    {
        id: 26,
        name: "jojer",
        front: "Joker",
        revert: "Joker Ters",
    },
    {
        id: 27,
        name: "tilsim-krali",
        front: "Tılsımların Kralı",
        revert: "Tılsımların Kralı Ters",
    },
    {
        id: 28,
        name: "degnek-prensi",
        front: "Değnek Prensi",
        revert: "Değnek Prensi Ters",
    },
    {
        id: 29,
        name: "aziz",
        front: "Aziz",
        revert: "Aziz Ters",
    },
    {
        id: 30,
        name: "asiklar",
        front: "Aşıklar",
        revert: "Aşıklar Ters",
    },
    {
        id: 31,
        name: "denge",
        front: "Denge",
        revert: "Denge Ters",
    },
    {
        id: 32,
        name: "kupa-kralicesi",
        front: "Kupaların Kraliçesi",
        revert: "Kupaların Kraliçesi Ters",
    },
    {
        id: 33,
        name: "adalet",
        front: "Adalet",
        revert: "Adalet Ters",
    },
    {
        id: 34,
        name: "tilsim-sovalyesi",
        front: "Tılsımların Şövalyesi",
        revert: "Tılsımların Şövalyesi Ters",
    },
    {
        id: 35,
        name: "degnek-kralicesi",
        front: "Değnek Kraliçesi",
        revert: "Değnek Kraliçesi Ters",
    },
    {
        id: 36,
        name: "imparator",
        front: "İmparator",
        revert: "İmparator Ters",
    },
    {
        id: 37,
        name: "kupa-krali",
        front: "Kupaların Kralı",
        revert: "Kupaların Kralı Ters",
    },
    {
        id: 38,
        name: "yildiz",
        front: "Yıldız",
        revert: "Yıldız Ters",
    },
    {
        id: 39,
        name: "degnek-sovalyesi",
        front: "Değnek Şövalyesi",
        revert: "Değnek Şövalyesi Ters",
    },
    {
        id: 40,
        name: "gunes",
        front: "Güneş",
        revert: "Güneş Ters",
    },
    {
        id: 41,
        name: "kader-carki",
        front: "Kader Çarkı",
        revert: "Kader Çarkı Ters",
    },
    {
        id: 42,
        name: "degnek-asi",
        front: "Değnek Ası",
        revert: "Değnek Ası Ters",
    },
    {
        id: 43,
        name: "degnek-altilisi",
        front: "Değnek Altılısı",
        revert: "Değnek Altılısı Ters",
    },
    {
        id: 44,
        name: "kupa-ikilisi",
        front: "Kupaların İkilisi",
        revert: "Kupaların İkilisi Ters",
    },
    {
        id: 45,
        name: "kiliclarin-beslisi",
        front: "Kılıçların Beşlisi",
        revert: "Kılıçların Beşlisi Ters",
    },
    {
        id: 46,
        name: "kiliclarin-onlusu",
        front: "Kılıçların Onlusu",
        revert: "Kılıçların Onlusu Ters",
    },
    {
        id: 47,
        name: "tilsim-dokuzlusu",
        front: "Tılsımların Dokuzlusu",
        revert: "Tılsımların Dokuzlusu Ters",
    },
    {
        id: 48,
        name: "degnek-uclusu",
        front: "Değnek Üçlüsü",
        revert: "Değnek Üçlüsü Ters",
    },
    {
        id: 49,
        name: "kupa-sekizlisi",
        front: "Kupaların Sekizlisi",
        revert: "Kupaların Sekizlisi Ters",
    },
    {
        id: 50,
        name: "tilsim-yedilisi",
        front: "Tılsımların Yedilisi",
        revert: "Tılsımların Yedilisi Ters",
    },
    {
        id: 51,
        name: "kupa-yedilisi",
        front: "Kupaların Yedilisi",
        revert: "Kupaların Yedilisi Ters",
    },
    {
        id: 52,
        name: "kupa-onlusu",
        front: "Kupaların Onlusu",
        revert: "Kupaların Onlusu Ters",
    },
];


export default TarotCards;