monolog:
    channels:
        - deprecation # Deprecations are logged in the dedicated "deprecation" channel when it exists
        - tarot

when@dev:
    monolog:
        handlers:
            tarot:
                type: rotating_file
                path: "%kernel.logs_dir%/tarot/%kernel.environment%.log"
                level: debug
                channels: [ "tarot" ]
                max_files: 10
            main:
                type: rotating_file
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug
                channels: ["!event"]
                max_files: 10
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine", "!console"]

when@test:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                channels: ["!event"]
            nested:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug

when@prod:
    monolog:
        handlers:
            main:
                type: rotating_file
                level: error
                excluded_http_codes: [404, 405]
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                max_files: 10
            nested:
                type: stream
                path: php://stderr
                level: debug
                formatter: monolog.formatter.json
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine"]
            deprecation:
                type: stream
                channels: [deprecation]
                path: php://stderr
                formatter: monolog.formatter.json
            tarot:
                type: rotating_file
                path: "%kernel.logs_dir%/tarot/%kernel.environment%.log"
                level: debug
                channels: ["tarot"]
                max_files: 10

