security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
        App\Entity\User:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        login:
            pattern: /api/login
            stateless: true
            json_login:
                check_path: /api/login
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
                username_path: email

        api:
            provider: app_user_provider
            pattern:   /api
            stateless: true
            jwt: ~

    access_control:
        - { path: /api/login, roles: PUBLIC_ACCESS }
        - { path: /api/register, roles: PUBLIC_ACCESS }
        - { path: /api,       roles: IS_AUTHENTICATED_FULLY }