security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
        App\Entity\User:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        login:
            pattern: ^/api/login
            stateless: true
            json_login:
                check_path: /api/login # or api_login_check as defined in config/routes.yaml
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
                username_path: email

        register:
            pattern: ^/api/register
            stateless: true
            security: false

        google_login:
            pattern: ^/api/connect/google
            stateless: true
            security: false

        google_check:
            pattern: ^/api/connect/google/check
            stateless: true
            security: false

        apple_check:
            pattern: ^/api/connect/apple
            stateless: true
            security: false

        api:
            provider: app_user_provider
            pattern:   /api
            stateless: true
            jwt: ~

    access_control:
        - { path: ^/api/connect/google, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/connect/google/check, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/connect/apple, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: /api,       roles: IS_AUTHENTICATED_FULLY }